//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreX.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreX.Domain.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string General_Entiy {
            get {
                return ResourceManager.GetString("General_Entiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string General_Filed {
            get {
                return ResourceManager.GetString("General_Filed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Invariant_EntityWasNotFound {
            get {
                return ResourceManager.GetString("Invariant_EntityWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Invariant_TheEntityWasArchivedSoArchivingItAgainIsNotPossible {
            get {
                return ResourceManager.GetString("Invariant_TheEntityWasArchivedSoArchivingItAgainIsNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Invariant_TheEntityWasNotArchivedSoRestoringItIsNotPossible {
            get {
                return ResourceManager.GetString("Invariant_TheEntityWasNotArchivedSoRestoringItIsNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Invariant_TheEntityWithThisSpecificationHasAlreadyBeenExisted {
            get {
                return ResourceManager.GetString("Invariant_TheEntityWithThisSpecificationHasAlreadyBeenExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_FieldCanNotBeEmpty {
            get {
                return ResourceManager.GetString("Validation_FieldCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_FieldIsNotAValidEmailAddress {
            get {
                return ResourceManager.GetString("Validation_FieldIsNotAValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_FieldLengthIsLessThanMinimumLengthLimit {
            get {
                return ResourceManager.GetString("Validation_FieldLengthIsLessThanMinimumLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_FieldLengthIsMoreThanMaximumLengthLimit {
            get {
                return ResourceManager.GetString("Validation_FieldLengthIsMoreThanMaximumLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_MaxLengthShouldBeAttributeMustHaveAValidLength {
            get {
                return ResourceManager.GetString("Validation_MaxLengthShouldBeAttributeMustHaveAValidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_MinLengthShouldBeAttributeMustHaveAValidLength {
            get {
                return ResourceManager.GetString("Validation_MinLengthShouldBeAttributeMustHaveAValidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_ValidationError {
            get {
                return ResourceManager.GetString("Validation_ValidationError", resourceCulture);
            }
        }
    }
}
