//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreX.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreX.Domain.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Invariant_Issue_AnEntityWasArchivedSoArchivingItAgainIsNotPossible {
            get {
                return ResourceManager.GetString("Invariant_Issue_AnEntityWasArchivedSoArchivingItAgainIsNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Invariant_Issue_InvariantError {
            get {
                return ResourceManager.GetString("Invariant_Issue_InvariantError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Invariant_Issue_NoEntityWasArchivedSoRestoringItIsNotPossible {
            get {
                return ResourceManager.GetString("Invariant_Issue_NoEntityWasArchivedSoRestoringItIsNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Invariant_Issue_NoEntityWasFound {
            get {
                return ResourceManager.GetString("Invariant_Issue_NoEntityWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Logical_Issue_AnEntityWithTheseConditionsOfExistenceHasAlreadyBeenExisted {
            get {
                return ResourceManager.GetString("Logical_Issue_AnEntityWithTheseConditionsOfExistenceHasAlreadyBeenExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Logical_Issue_LogicalError {
            get {
                return ResourceManager.GetString("Logical_Issue_LogicalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_Issue_FieldCanNotBeEmpty {
            get {
                return ResourceManager.GetString("Validation_Issue_FieldCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_Issue_FieldIsNotAValidEmailAddress {
            get {
                return ResourceManager.GetString("Validation_Issue_FieldIsNotAValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_Issue_FieldLengthIsLessThanMinimumLengthLimit {
            get {
                return ResourceManager.GetString("Validation_Issue_FieldLengthIsLessThanMinimumLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_Issue_FieldLengthIsMoreThanMaximumLengthLimit {
            get {
                return ResourceManager.GetString("Validation_Issue_FieldLengthIsMoreThanMaximumLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_Issue_MaxLengthShouldBeAttributeMustHaveAValidLength {
            get {
                return ResourceManager.GetString("Validation_Issue_MaxLengthShouldBeAttributeMustHaveAValidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_Issue_MinLengthShouldBeAttributeMustHaveAValidLength {
            get {
                return ResourceManager.GetString("Validation_Issue_MinLengthShouldBeAttributeMustHaveAValidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_Issue_StartDateCanNotBeLaterThanEndDate {
            get {
                return ResourceManager.GetString("Validation_Issue_StartDateCanNotBeLaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Validation_Issue_ValidationError {
            get {
                return ResourceManager.GetString("Validation_Issue_ValidationError", resourceCulture);
            }
        }
    }
}
